/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.io.IOException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import lleak.channel.ChanCol;
import lleak.helpers.*;

/**
 *
 * @author tassy
 */
public class ChanMenu extends javax.swing.JDialog {

    private DefaultListModel<String> lmod = new DefaultListModel<>();
    private DefaultListModel<String> lmod3 = new DefaultListModel<>();
    private DefaultListModel<String> lmod4 = new DefaultListModel<>();
    ArrayList<ChanCol> columns = null;
    private MainMenu parent;

    /**
     * Creates new form ChanMenu
     */
    public ChanMenu(MainMenu parent) {
        this.parent = parent;
        initComponents();
        setInf();
        jList1.setModel(lmod);
        jList3.setModel(lmod3);
        lmod4.clear();
        jList4.setModel(lmod4);
        setLocationRelativeTo(parent);
    }

    private void setInf() {
        lmod.clear();
        ChanProfReader cpr = new ChanProfReader(parent.getRootDir() + parent.getCr().getChan());
        cpr.getChans().stream().forEach(s -> lmod.addElement(s.getFile()));

        columns = ChanCol.readCSV(parent.getRootDir() + "meta.csv");
        lmod3.clear();
        //ArrayList<ChanCol> cols = cf.getColumns();
        for (ChanCol c : columns) {
            if (!c.getVarname().equals("x") && !c.getVarname().equals("t")) {
                lmod3.addElement(c.getFullname());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        jButton7.setText("Очистить выбор");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Выбрать всё");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jButton1.setText("Выбрать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        jButton5.setText(">>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("<<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jLabel1.setText("Выберите канал:");

        jLabel2.setText("Выберите переменные для отображения:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel3.setText("Выберите тип графика:");

        jRadioButton1.setText("Динамика параметров");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Профиль параметров");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton2.setText("Назад");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton9.setText("Очистить выбор");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Выбрать всё");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(7, 7, 7))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addGap(116, 116, 116)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton6)
                                    .addComponent(jButton5))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4)))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2))
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // back
        this.setVisible(false);
        parent.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // select arg
        String selVal = jList3.getSelectedValue();
        int ind = jList3.getSelectedIndex();
        if (!selVal.isEmpty()) {
            lmod4.addElement(selVal);
            lmod3.remove(ind);
            jList3.setModel(lmod3);
            jList4.setModel(lmod4);

            //TODO: сортировка списков после добавления/удаления
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // unselect arg
        String selVal = jList4.getSelectedValue();
        int ind = jList4.getSelectedIndex();
        if (!selVal.isEmpty()) {
            lmod3.addElement(selVal);
            lmod4.remove(ind);
            jList3.setModel(lmod3);
            jList4.setModel(lmod4);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // clear

        lmod3.clear();
        for (ChanCol c : columns) {
            lmod3.addElement(c.getFullname());
        }
        jList3.setModel(lmod3);
        lmod4.clear();
        jList4.setModel(lmod4);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // select all

        lmod4.clear();
        for (ChanCol c : columns) {
            lmod4.addElement(c.getFullname());
        }
        jList4.setModel(lmod4);

        lmod3.clear();
        jList3.setModel(lmod3);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // clear

        lmod3.clear();
        for (ChanCol c : columns) {
            lmod3.addElement(c.getFullname());
        }
        jList3.setModel(lmod3);
        lmod4.clear();
        jList4.setModel(lmod4);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // select all

        lmod4.clear();
        for (ChanCol c : columns) {
            lmod4.addElement(c.getFullname());
        }
        jList4.setModel(lmod4);

        lmod3.clear();
        jList3.setModel(lmod3);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // select

        boolean dyn = jRadioButton1.isSelected();
        boolean prof = jRadioButton2.isSelected();

        String selChan = null;
        selChan = jList1.getSelectedValue();

        String strSelParams = null;
        if (lmod4.isEmpty()) {
            System.out.println("error");
        } else {

            ArrayList<String> arr = new ArrayList<>();
            ArrayList<String> selParams = new ArrayList<>();
            Enumeration<String> params = lmod4.elements();

            while (params.hasMoreElements()) {
                arr.add(params.nextElement());
            }

            for (String s : arr) {
                for (ChanCol c : columns) {
                    if (s.equals(c.getFullname())) {
                        selParams.add(c.getVarname());
                    }

                }
            }
            strSelParams = selParams.toString().replaceAll("\\n", ",").replaceAll("[\\]\\[]", "");
        }

        //графики для динамики
        if (dyn) {
            ChanTxtReader ctr = new ChanTxtReader(parent.getRootDir() + selChan);
            GeomReader gr = new GeomReader(parent.getRootDir() + ctr.getGeom());

            DecimalFormatSymbols dfs = new DecimalFormatSymbols();
            dfs.setDecimalSeparator('.');
            DecimalFormat decimalFormat = new DecimalFormat("#.####");
            decimalFormat.setDecimalFormatSymbols(dfs);

            ArrayList<Double> pointsInTime = gr.getChanCoord();
            ArrayList<String> selVals = new ArrayList<>();
            for (Double p : pointsInTime) {
                selVals.add(decimalFormat.format(p));
            }
            String strSelVals = selVals.toString().replaceAll("\\n", ",").replaceAll("[\\]\\[]", "");

            String rDir = "\"" + parent.getRDir() + "Rscript.exe" + "\"";
            ProcessBuilder processBuilder = new ProcessBuilder("script.bat", rDir, parent.getRootDir() 
                +  ctr.getOutfile(), parent.getRootDir() + "meta.csv", strSelVals, strSelParams, "d");
            Process p;

            try {
                p = processBuilder.start();
                p.waitFor();
                System.out.println("Done");

            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(ParamDynamicsMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                java.util.logging.Logger.getLogger(ParamDynamicsMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        //графики для профиля
        if (prof) {
            ChanTxtReader ctr = new ChanTxtReader(parent.getRootDir() + selChan);
            TimeReader tr = new TimeReader(parent.getRootDir() + parent.getCr().getTime());

            DecimalFormatSymbols dfs = new DecimalFormatSymbols();
            dfs.setDecimalSeparator('.');
            DecimalFormat decimalFormat = new DecimalFormat("#.####");
            decimalFormat.setDecimalFormatSymbols(dfs);

            ArrayList<Double> pointsInTime = tr.getPointsInTime();
//            ArrayList<String> selVals = new ArrayList<>();
//            for (Double p: pointsInTime){
//                selVals.add(decimalFormat.format(p));
//            }
//            String strSelVals = selVals.toString().replaceAll("\\n", ",").replaceAll("[\\]\\[]", "");
//            ProcessBuilder processBuilder = new ProcessBuilder("script.bat", parent.getRootDir() + ctr.getOutfile(), parent.getRootDir()
//                    + "meta.csv", strSelVals, strSelParams, "p");
//            Process p1;
//            try {
//                p1 = processBuilder.start();
//                p1.waitFor();
//                System.out.println("Done");
//
//            } catch (IOException ex) {
//                java.util.logging.Logger.getLogger(ParamDynamicsMenu.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (InterruptedException ex) {
//                java.util.logging.Logger.getLogger(ParamDynamicsMenu.class.getName()).log(Level.SEVERE, null, ex);
//            }
            
            ArrayList<String> selVals1 = new ArrayList<>();
            for (int i = 0; i< pointsInTime.size()/2; i++) {
                selVals1.add(decimalFormat.format(pointsInTime.get(i)));
            }
            String strSelVals1 = selVals1.toString().replaceAll("\\n", ",").replaceAll("[\\]\\[]", "");
            
            ArrayList<String> selVals2 = new ArrayList<>();
            for (int i = pointsInTime.size()/2; i< pointsInTime.size(); i++) {
                selVals2.add(decimalFormat.format(pointsInTime.get(i)));
            }
            String strSelVals2 = selVals2.toString().replaceAll("\\n", ",").replaceAll("[\\]\\[]", "");
            
            String rDir = "\"" + parent.getRDir() + "Rscript.exe" + "\"";
        
            ProcessBuilder processBuilder1 = new ProcessBuilder("script.bat", rDir, parent.getRootDir() + ctr.getOutfile(), parent.getRootDir()
                    + "meta.csv", strSelVals1, strSelParams, "p");
            Process p1;
            try {
                p1 = processBuilder1.start();
                p1.waitFor();
                System.out.println("Done");

            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(ParamDynamicsMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) { 
                Logger.getLogger(ChanMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            ProcessBuilder processBuilder2 = new ProcessBuilder("script.bat", rDir, parent.getRootDir() + ctr.getOutfile(), parent.getRootDir()
                    + "meta.csv", strSelVals2, strSelParams, "p");            
            Process p2;
            try {
                p2 = processBuilder2.start();
                p2.waitFor();
                System.out.println("Done");

            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(ParamDynamicsMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(ChanMenu.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
